# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logins', '0002_auto_20161114_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('blog', models.TextField(max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logins.User')),
            ],
        ),
    ]
